### ISSUE TITLE
error when run val_dataset.run_eval(preds, cfg.OUTPUT_DIR)

### ISSUE THREAD

**Issue by murdockhou** [tensorboy/centerpose#18]
I have test the train process using first 100 samples of MSCOCO. The cmd of training is 
```
 python3 train.py --cfg ../experiments/mobilenetv3_512x512.yaml
```
and when run mAP calculate in line 121 of `train.py`, I got an error like this:
![Selection_207](https://user-images.githubusercontent.com/18358653/71651389-10c5ec80-2d58-11ea-9492-62af178c36d1.png)
but when I run 
```
python3 evaluate.py --cfg ../experiments/mobilenetv3_512x512.yaml --NMS false --TESTMODEL ../models/model_zoo/mobilenetV3_1x.pth
```
It's ok and can output result.
![image](https://user-images.githubusercontent.com/18358653/71651831-9eefa200-2d5b-11ea-9f15-92f27194cadc.png)

Update:
Maybe change code like this will be work in [here](https://github.com/tensorboy/centerpose/blob/master/lib/trains/multi_pose.py#L164)
```
dets_out = np.concatenate(
    [detection[1] for detection in dets_out], axis=0).astype(np.float32)           
if self.cfg.TEST.NMS or len(self.cfg.TEST.TEST_SCALES) > 1:
    soft_nms_39(dets_out, Nt=0.5, method=2)
dets_out = dets_out.tolist()
# results[batch['meta']['img_id'].cpu().numpy()[0]] = dets_out[0]
results[batch['meta']['img_id'].cpu().numpy()[0]] = dets_out
```

**Comment by tensorboy** [comment]
Hi @murdockhou 

The bug fixed and it should be work now.

Thanks for the comments and suggestions. :)

**Comment by murdockhou** [comment]
@tensorboy I pull the lateset repo and get the same error too. Please check this, I only change `.yaml ` file and change `images = self.coco.getImgIds()` code in `coco_hp.py` into `images = self.coco.getImgIds()[:100]` for only test. And get the same error as before mentioned.

**Comment by tensorboy** [comment]
Sure, will double check tmr!

**Comment by murdockhou** [comment]
@tensorboy Hi, I find you have changed `results[batch['meta']['img_id'].cpu().numpy()[0]] = dets_out[0]` to `results[batch['meta']['img_id'].cpu().numpy()[0]] = {1:dets_out[0]}` in `lib/trains/multi_pose.py`. Which difference is if I write like this
 ```
dets_out = np.concatenate( 
    [detection[1] for detection in dets_out], axis=0).astype(np.float32) 

results[batch['meta']['img_id'].cpu().numpy()[0]] = dets_out
```  
And by the way, can I get your trian `log.txt` file about mobilenetv3  backbone network, I start to train this using mobilenetv3 but the mAP of the first 10 epochs is too small.
