### ISSUE TITLE
too many values to unpack (expected 2)!

### ISSUE THREAD

**Issue by bleakie** [tensorboy/centerpose#3]
At  'results, meta = results[0]' ,got this error

**Comment by Byronnar** [comment]
same problem with you...

**Comment by bleakie** [comment]
I use cu90+torch1.1， something wrong？

**Comment by tensorboy** [comment]
Hi @bleakie and @Byronnar That's my bad, will update code tmr.

**Comment by bleakie** [comment]
我傻傻的调试了一天，so sad

**Comment by Byronnar** [comment]
> Hi @bleakie and @Byronnar That's my bad, will update code tmr.

请问现在还不可以么？ 刚刚试了下还是不行

**Comment by murdockhou** [comment]
Same error. And I got warning like this: 
```
No param head_model.hps.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param head_model.reg.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param head_model.reg.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.

```
The command line is :
```
python3 demo.py --cfg ../experiments/hardnet_512x512.yaml --TESTMODEL ../models/hardnet_best.pth --DEMOFILE ../images/image1.jpg --DEBUG 1 --NMS False
```
@tensorboy

**Comment by tensorboy** [comment]
Hi @murdockhou This is because I separate the backbone and head... I will fix this issue today.

**Comment by tensorboy** [comment]
Hi @bleakie @Byronnar @murdockhou 

Thanks for the patience, the bug fixed and you can download the most recent model to have a try. Let me know if it still not work.

**Comment by zhangyunming** [comment]
i have test dla34 mobile3 hardnet ,dla34 and hardnet can work but hardnet have a poor result , mobile3 can not work ，does mobile3 weight is the right one ?

**Comment by tensorboy** [comment]
Hi @zhangyunming The hardnet currently really have poor result... I'm looking for whether I can improve the result...

I test the mobilenetV3 model 1 hour ago, will double confirm mobile3's result tmr.

**Comment by zhangyunming** [comment]
hi @tensorboy the mobile3 weight named "mobilenetV3_1x.pth",but all others named _bast.pth ,does it  is a pretrained model trained by the data of  imagenet?

the error as below:

No param head_model.hm_hp.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param head_model.hm_hp.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param head_model.hm_hp.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param head_model.hp_offset.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param head_model.hp_offset.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param head_model.hp_offset.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param head_model.hp_offset.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.

**Comment by tensorboy** [comment]
Hi @zhangyunming THis error is because I separate the head with backbone, and I updated the model 2 hours ago.

Is your model the newest?

**Comment by zhangyunming** [comment]
oh,sorry  the model of mobile3  is downloaded yestorday, i will get the lastest weights for a test.

**Comment by Byronnar** [comment]
> Hi @zhangyunming THis error is because I separate the head with backbone, and I updated the model 2 hours ago.
> 
> Is your model the newest?

new error...
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:425

os :ubuntu18.04.3
torch version : 1.1
cuda: 10.0
cudnn:7.3
 it cannot work?

However, cuda is avialiable
>>> import torch
>>> torch.cuda.is_available()
True

**Comment by tensorboy** [comment]
@Byronnar  What is your GPU brand, is it 2080ti?

**Comment by Byronnar** [comment]
> @Byronnar What is your GPU brand, is it 2080ti?

1080

**Comment by tensorboy** [comment]
I fixed a similar problem by: `pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl`..... You may need to have a search for this.

**Comment by murdockhou** [comment]
@tensorboy Thanks for your work! I have test MobilenetV3 && hardnet, all works. But a problem is that the parameter --NMS is not work well. When I set --NMS False or just change the default value of --NMS to False, the code in `lib/detectors/multi_pose.py` line 76 77 will be run, and I print the value of  
```
print (self.cfg.TEST.NMS)
print (len(self.cfg.TEST.TEST_SCALES))
```
is 
```
True
1
```
Because I compile NMS error and will not use multi-scale testing, so I just did not need nms. Please check this, thanks~

**Comment by tensorboy** [comment]
@murdockhou will update it ASAP.

**Comment by Byronnar** [comment]
> I fixed a similar problem by: `pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl`..... You may need to have a search for this.

thank you , I solved the problem by the code:
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch

**Comment by bleakie** [comment]
A bug        

if phase == 'train':
            model = self.model #需要把这个定义放在外面，要不然val的时候没有定义
            self.model.train()
        else:
            if len(self.cfg.GPUS) > 1:
                model = self.model.module        
            model.eval()

lib/trains/base_trainer.py

**Comment by bleakie** [comment]
请教：我想把keypoint减少到10个，但是在coco_eval.evaluate()的时候会出现10与17点的不匹配，请问是需要在COCOeval里面修改吗？or else

**Comment by tensorboy** [comment]
@bleakie 这个需要改pycocotools的源码了。

**Comment by tensorboy** [comment]
@bleakie 这个bug已经修复了。

**Comment by bleakie** [comment]
两个问题：
1.训练的时候可以加载预训练模型这样会更fun一些
2.coco_hp.py的convert_eval_format是不是应该改成以下，原版有bug
 for image_id in all_bboxes:
      for cls_ind in all_bboxes[image_id]:
            category_id = 1
            for dets in all_bboxes[image_id][cls_ind]:

**Comment by tensorboy** [comment]
@bleakie 这个bug应该已经修复了。

**Comment by tensorboy** [comment]
Hi @murdockhou I did not reproduce your error, it works well on my side...

**Comment by murdockhou** [comment]
@tensorboy Thanks for your tring, I'll check this by myself.

**Comment by bleakie** [comment]
convert2onnx.py   
ONNX export failed: Couldn't export Python operator _DCNv2

**Comment by tensorboy** [comment]
@bleakie export 个resnet试试， onnx和tensorrt没有DCN这种层。

**Comment by bleakie** [comment]
我现在训练的是mobilenet的模型，也就是说不可以转onnx吗？如果可以，该怎么做呢？

**Comment by tensorboy** [comment]
目前的mobilenet里面有DCN，应该没法转，可以试试把DCN换成其他的

**Comment by Lakerszjb** [comment]
请问为什么比原版论文里以DLA-34为backbone指标高了这么多啊 hourglass的有测吗？谢谢~

**Comment by bleakie** [comment]
我看到一个使用 mobilenetv2的backbone，没有利用DCN，但是模型的输出不一致，请问可以修改吗？
https://github.com/CaoWGG/Mobilenetv2-CenterNet

**Comment by tensorboy** [comment]
Hi @Lakerszjb, 参数一直调mAP就会一直涨哈哈，感觉hourglass太大了一直不想去训练。。。

**Comment by tensorboy** [comment]
@bleakie Here is the mobilenetV2:https://github.com/tensorboy/centerpose/blob/master/experiments/mobilenetv2_512x512.yaml

I don't have enough GPUs to train it, you can debug and do it by yourself. :)

**Comment by bleakie** [comment]
请教：在利用convert2onnx.py转成onnx之后，怎样测试转成的onnx模型的效果呢？我face/demo.py，并不成功

**Comment by LouisNUST** [comment]
Traceback (most recent call last):
  File "/home/centerpose/tools/train.py", line 151, in <module>
    main(cfg, local_rank)
  File "/home/centerpose/tools/train.py", line 120, in main
    mAP = val_dataset.run_eval(preds, cfg.OUTPUT_DIR)
  File "/home/centerpose/tools/../lib/datasets/coco_hp.py", line 100, in run_eval
    coco_dets = self.coco.loadRes(self.convert_eval_format(results))        
  File "/home/centerpose/tools/../lib/datasets/coco_hp.py", line 64, in convert_eval_format
    bbox = dets[:4]
IndexError: invalid index to scalar variable.
